import { writeFileSync } from "node:fs";

const tenantTables = [
  "subscriptions",
  "team_members",
  "client_notes",
  "client_status_events",
  "client_tag_assignments",
  "client_tags",
  "clients",
  "exercise_aliases",
  "exercise_categories",
  "exercise_favorites",
  "exercise_hidden",
  "exercises",
  "foods",
  "meal_items",
  "meal_log_items",
  "meal_logs",
  "meals",
  "nutrition_assignments",
  "nutrition_plans",
  "assignment_session_overrides",
  "block_exercise_alternatives",
  "block_exercises",
  "exercise_blocks",
  "program_assignments",
  "program_macrocycles",
  "program_mesocycles",
  "program_microcycles",
  "program_sessions",
  "program_weeks",
  "programs",
  "set_prescriptions",
  "recipe_ingredients",
  "recipes",
  "session_logs",
  "set_logs",
  "assessment_fields",
  "assessment_responses",
  "assessment_templates",
  "assessments",
  "feedback_questions",
  "feedback_responses",
  "session_feedback",
  "session_feedback_templates",
  "habit_assignments",
  "habit_logs",
  "habits",
  "coach_profiles",
  "coach_services",
  "availability_rules",
  "blocked_dates",
  "bookings",
  "promo_codes",
  "payments",
  "revenue_snapshots",
  "notification_logs",
  "notification_templates",
  "push_subscriptions",
  "conversation_participants",
  "conversations",
  "messages",
  "drive_files",
  "drive_folders",
  "drive_shares",
  "video_access",
  "video_categories",
  "videos",
  "action_logs",
  "automation_actions",
  "automation_executions",
  "automations",
  "coach_tasks",
  "questionnaire_questions",
  "questionnaire_responses",
  "questionnaire_schedules",
  "questionnaire_submissions",
  "questionnaires",
  "coaching_pathways",
  "pathway_enrollments",
  "pathway_step_logs",
  "pathway_steps",
  "api_keys",
  "webhook_deliveries",
  "webhook_endpoints",
  "referral_codes",
  "referral_conversions",
  "referral_credit_balances",
  "referral_credit_ledger",
  "referral_programs",
  "audit_logs",
];

const lines: string[] = [
  "-- Enable row-level security for multi-tenant isolation (P6.1)",
  "",
  "ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;",
  "ALTER TABLE organizations FORCE ROW LEVEL SECURITY;",
  "CREATE POLICY tenant_isolation ON organizations FOR ALL",
  "  USING (",
  "    id = current_setting('app.organization_id', true)",
  "    OR current_setting('app.bypass_rls', true) = 'true'",
  "  );",
  "",
];

for (const table of tenantTables) {
  lines.push(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;`);
  lines.push(`ALTER TABLE ${table} FORCE ROW LEVEL SECURITY;`);
  lines.push(`CREATE POLICY tenant_isolation ON ${table} FOR ALL`);
  lines.push("  USING (");
  lines.push(
    "    organization_id = current_setting('app.organization_id', true)",
  );
  lines.push("    OR current_setting('app.bypass_rls', true) = 'true'");
  lines.push("  );");
  lines.push("");
}

writeFileSync("lib/db/migrations/0030_enable_rls.sql", lines.join("\n"));
console.log("Wrote lib/db/migrations/0030_enable_rls.sql");
